apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-cubix-cn.fullname" . }}
  labels:
    release: monitoring
    {{- include "spring-cubix-cn.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "spring-cubix-cn.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 10s